apiVersion: v1
kind: Service
metadata:
  name: rf005-app-service
spec:
  # Using NodePort or ClusterIP depending on exposure needs, standard API gateway will route to it.
  type: ClusterIP
  selector:
    app: rf005-app
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
